version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: homeowner_postgres
    environment:
      POSTGRES_DB: homeowner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1488
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build:
      context: ../backend_team_A
      dockerfile: dockerfile
    container_name: homeowner_backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/homeowner
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1488
      JWT_SECRET: MySuperSecretKeyForJWTThatIsAtLeast32CharactersLong1234567890148822869teamA148822869
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ../project-front
      dockerfile: dockerfile
    container_name: homeowner_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge